databases:
  - name: employee-management-db
    databaseName: employee_management
    user: employee_user

services:
  - type: web
    name: employee-management-web
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: employee-management-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False