# Generated by Django 5.2.1 on 2025-05-22 11:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_delete_employeedocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('certificate_type', models.CharField(choices=[('professional', 'Professional Certification'), ('safety', 'Safety Certification'), ('compliance', 'Compliance Certificate'), ('training', 'Training Certificate'), ('license', 'License'), ('other', 'Other')], max_length=50)),
                ('issuing_authority', models.CharField(max_length=200)),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('expiring_soon', 'Expiring Soon'), ('pending_renewal', 'Pending Renewal')], default='active', max_length=20)),
                ('certificate_file', models.FileField(upload_to='certificates/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('reminder_days_before', models.IntegerField(default=30, help_text='Days before expiry to send reminder')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='employees.employee')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('headcount', 'Headcount Report'), ('attrition', 'Attrition Report'), ('leave_utilization', 'Leave Utilization Report'), ('certificate_expiry', 'Certificate Expiry Report'), ('custom', 'Custom Report')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('once', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='once', max_length=20)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('filters', models.JSONField(default=dict, help_text='Filters applied to the report')),
                ('columns', models.JSONField(default=list, help_text='Columns to include in the report')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('email_recipients', models.JSONField(default=list, help_text='Email addresses to send scheduled reports')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xlsx', 'csv'])])),
                ('error_message', models.TextField(blank=True)),
                ('execution_time', models.DurationField(blank=True, null=True)),
                ('record_count', models.IntegerField(blank=True, null=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='analytics.report')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='HRMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('headcount', 'Headcount'), ('attrition_rate', 'Attrition Rate'), ('average_tenure', 'Average Tenure'), ('new_hires', 'New Hires'), ('terminations', 'Terminations'), ('leave_utilization', 'Leave Utilization'), ('diversity_ratio', 'Diversity Ratio'), ('promotion_rate', 'Promotion Rate')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date', models.DateField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('calculation_details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.department')),
            ],
            options={
                'ordering': ['-date', 'metric_type'],
                'unique_together': {('metric_type', 'date', 'department')},
            },
        ),
    ]
