# Generated by Django 5.2.1 on 2025-06-27 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('employees', '0005_tasktimelog_employeeattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='reportexecution',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
