# Generated by Django 5.2.1 on 2025-07-10 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boarding', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_assigned_by', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='equipmentassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_assigned_to', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='equipmentassignment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='boarding.equipment'),
        ),
        migrations.AddField(
            model_name='equipmentassignment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_returns', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='process',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_processes', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='process',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_processes', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='processtemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_process_templates', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='processtemplate',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='process_templates', to='employees.department'),
        ),
        migrations.AddField(
            model_name='process',
            name='process_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='boarding.processtemplate'),
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_departments', to='employees.department'),
        ),
        migrations.AddField(
            model_name='task',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='dependent_tasks', to='boarding.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_tasks', to='boarding.process'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_tasks', to='employees.department'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='dependent_tasks', to='boarding.tasktemplate'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='process_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='boarding.processtemplate'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='boarding.tasktemplate'),
        ),
    ]
