# Generated by Django 5.2.1 on 2025-06-26 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarding', '0001_initial'),
        ('employees', '0005_tasktimelog_employeeattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_processes', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_departments', to='employees.department'),
        ),
        migrations.AlterField(
            model_name='task',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_tasks', to='boarding.process'),
        ),
    ]
