# Generated by Django 5.2.1 on 2025-06-26 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarding', '0002_alter_process_employee_alter_task_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_tasks', to='boarding.process'),
        ),
    ]
