# Generated by Django 5.2.1 on 2025-06-26 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarding', '0005_alter_task_assignee'),
        ('employees', '0005_tasktimelog_employeeattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='employees.employee'),
        ),
    ]
