# Generated by Django 5.2.1 on 2025-06-26 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarding', '0007_alter_task_completed_by'),
        ('employees', '0005_tasktimelog_employeeattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_assigned_by', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='equipmentassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_assigned_to', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='equipmentassignment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_returns', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='process',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_processes', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='processtemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_process_templates', to='employees.employee'),
        ),
    ]
