# Generated by Django 5.2.1 on 2025-07-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarding', '0008_alter_equipmentassignment_assigned_by_and_more'),
        ('employees', '0006_employee_account_number_employee_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='employees.employee'),
        ),
    ]
