# Generated by Django 5.2.1 on 2025-05-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_id_employee_employee_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeDocument',
        ),
    ]
