# Generated by Django 5.2.1 on 2025-07-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_tasktimelog_employeeattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
